In [1]:
# 1. Feladat

import pandas as pd
df = pd.read_csv('games.csv', index_col=0)

df['Date'] = pd.to_datetime(df['Year'], format='%Y')

df['EU_Sales_%'] = (100 * df['EU_Sales'] / df['Global_Sales']).round(2)

df[df['Date'].dt.is_leap_year].loc[:50][['Name', 'Publisher', 'EU_Sales_%']]

                               Name                    Publisher  EU_Sales_%
Rank
3                    Mario Kart Wii                     Nintendo       35.96
5          Pokemon Red/Pokemon Blue                     Nintendo       28.34
10                        Duck Hunt                     Nintendo        2.23
18    Grand Theft Auto: San Andreas         Take-Two Interactive        1.92
23              Super Mario Bros. 3                     Nintendo       19.91
35       Call of Duty: Black Ops II                   Activision       41.91
36       Call of Duty: Black Ops II                   Activision       31.32
40          Super Smash Bros. Brawl                     Nintendo       20.02
47                   Super Mario 64                     Nintendo       23.97
48                   Gran Turismo 4  Sony Computer Entertainment        0.09

In [2]:
# 2. Feladat

import pandas as pd
import plotly.express as px

df = pd.read_csv('games.csv', index_col=0)

fig = px.scatter_3d(
    df, 
    x = 'NA_Sales', 
    y = 'EU_Sales', 
    z = 'JP_Sales', 
    color='Publisher', 
    hover_name='Name')
fig.show()

dfg = df.sort_values('Global_Sales').groupby(['Platform', 'Year'])

dfn = pd.DataFrame()
dfn['Best_game'] = dfg.last()['Name']
dfn['Total_sales'] = dfg['Global_Sales'].sum()
dfn.reset_index(inplace=True)

display(dfn)

fig2 = px.bar(
    dfn[dfn['Year']==2010], 
    x = 'Platform', 
    y = 'Total_sales',
    hover_name='Best_game')
fig2.show()

    Platform    Year                       Best_game  Total_sales
0       2600  1980.0                       Asteroids        11.38
1       2600  1981.0                        Pitfall!        35.77
2       2600  1982.0                         Pac-Man        28.86
3       2600  1983.0        Pitfall II: Lost Caverns         5.83
4       2600  1984.0                       Beamrider         0.27
..       ...     ...                             ...          ...
236       XB  2008.0                   Madden NFL 09         0.18
237     XOne  2013.0            Call of Duty: Ghosts        18.60
238     XOne  2014.0  Call of Duty: Advanced Warfare        52.43
239     XOne  2015.0       Call of Duty: Black Ops 3        57.66
240     XOne  2016.0       Tom Clancy's The Division        12.37

[241 rows x 4 columns]

In [3]:
# 3. Feladat

import pandas as pd
import plotly.express as px

df = pd.read_csv('games.csv', index_col=0)

dfy = df[df['Year']==2000]

dfr = dfy.loc[[
    dfy['NA_Sales'].idxmax(), 
    dfy['EU_Sales'].idxmax(), 
    dfy['JP_Sales'].idxmax(), 
    dfy['Other_Sales'].idxmax()]]
dfr.index = pd.Series(['NA', 'EU', 'JP', 'Other'])

display(dfr)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
NA,Tony Hawk's Pro Skater 2,PS,2000.0,Sports,Activision,3.05,1.41,0.02,0.20,4.68
EU,Driver 2,PS,2000.0,Action,Atari,2.36,2.10,0.02,0.25,4.73
JP,Dragon Quest VII: Warriors of Eden,PS,2000.0,Role-Playing,Enix Corporation,0.20,0.14,4.10,0.02,4.47
Other,Pokémon Crystal Version,GB,2000.0,Role-Playing,Nintendo,2.55,1.56,1.29,0.99,6.39